import "./globals.css";

import ClientProviders from "@/components/ClientProviders";
import FirebaseAuthProvider from "@/components/FirebaseAuthProvider";
import Header from "@/components/Header";
import type { Metadata } from "next";
import { SubscriptionProvider } from "@/components/SubscriptionProvider";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClientProviders>
			<html lang="en">
				<body className={"flex flex-col min-h-screen"}>
					<FirebaseAuthProvider>
						<SubscriptionProvider>
							<ThemeProvider
								attribute="class"
								defaultTheme="system"
								enableSystem
								disableTransitionOnChange
							>
								<Header />
								{children}
							</ThemeProvider>
						</SubscriptionProvider>
					</FirebaseAuthProvider>
				</body>
			</html>
		</ClientProviders>
	);
}
