import "./globals.css";

import ClientProviders from "@/components/ClientProviders";
import Header from "@/components/Header";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ThemeProvider";
import { auth } from "./api/auth/[...nextauth]/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <ClientProviders>
      <html lang="en">
        <body className={"flex flex-col min-h-screen"}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Header />
              {children}
            </ThemeProvider>
        </body>
      </html>
    </ClientProviders>
  );
}
